### ISSUE TITLE
PyPI release checklist

### ISSUE THREAD

**Issue by ml-evs** [Matgenix/jobflow-remote#53]
Just an issue to track some stuff that needs to be done before the first PyPI release (IMO):

- [ ] Merge #32, #52 and probably #51, perhaps also the PR that fixes type hints (#54)
- [ ] Make sure release workflow works (including docs build) -- currently only deploys to test PyPI
- [ ] Add link to JOSS paper in README?
- [ ] Clarify versioning wrt. jobflow: probably we should have pinned versions of jobflow in our tests, but free versioning in the `pyproject.toml`, with dependabot automatically running tests on new releases
- [ ] Potentially add one full-scale integration tests that runs a simple atomate workflow with jobflow-remote

**Comment by Andrew-S-Rosen** [comment]
This can be closed! :D
